language: python
cache: pip
dist: bionic
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO_VERSION=2.2.19
  - DJANGO_VERSION=3.0.13
  - DJANGO_VERSION=3.1.7
  - DJANGO_VERSION=2.2.19   DRF_VERSION=3.12.2
  - DJANGO_VERSION=3.0.13   DRF_VERSION=3.12.2
  - DJANGO_VERSION=3.1.7   DRF_VERSION=3.12.2
install:
  - pip install -r .travis/requirements.txt
  - pip install --upgrade "Django==${DJANGO_VERSION}"
  - if [[ $DRF_VERSION ]]; then pip install --upgrade djangorestframework==${DRF_VERSION}; fi
script: python runtests.py
